### ISSUE TITLE
migrate to organization ?

### ISSUE THREAD

**Issue by ZYSzys** [personalized-news/text-similarity#2]
/cc @yewenjunfighting

**Comment by codewizardTM** [comment]
可以

**Comment by ZYSzys** [comment]
=> https://github.com/yewenjunfighting/Text-similarity-algorithm/settings

![screen shot 2019-02-10 at 9 32 19 pm](https://user-images.githubusercontent.com/23313266/52534340-6a59ad00-2d7b-11e9-8dbc-9662768443b7.png)

![screen shot 2019-02-10 at 9 33 26 pm](https://user-images.githubusercontent.com/23313266/52534351-86f5e500-2d7b-11e9-8f52-c77562512d9f.png)
